# Generated by Django 5.0.7 on 2024-07-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(choices=[('DUVIDAS', 'Dúvidas/informações'), ('SOLICITACOES', 'Solicitações'), ('ELOGIOS', 'Elogios'), ('SUGESTOES', 'Sugestões'), ('RECLAMACOES', 'Reclamações')], max_length=50)),
                ('mensagem', models.TextField()),
            ],
        ),
    ]
